# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 23:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=12)),
                ('endereco', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='agenda',
            name='data_hora_Inicio',
            field=models.DateTimeField(max_length=50),
        ),
        migrations.AddField(
            model_name='usuario',
            name='agendas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.Agenda'),
        ),
    ]
