# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_auto_20170918_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='agendas',
        ),
        migrations.AddField(
            model_name='usuario',
            name='agendas',
            field=models.ManyToManyField(to='agenda.Agenda'),
        ),
    ]
