# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_auto_20170918_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='descricao',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
