# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 23:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_agenda_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgPrivada',
            fields=[
                ('agenda_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='agenda.Agenda')),
                ('login', models.CharField(max_length=20)),
                ('senha', models.CharField(max_length=8)),
                ('usuarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.Usuario')),
            ],
            bases=('agenda.agenda',),
        ),
        migrations.RenameField(
            model_name='agenda',
            old_name='descricao',
            new_name='tarefa',
        ),
        migrations.AddField(
            model_name='agenda',
            name='compromisso',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
