# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 23:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_auto_20170918_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendaprivada',
            name='usuarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.Usuario'),
        ),
    ]
