# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 00:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0008_auto_20170918_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendaprivada',
            name='usuarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.Usuario'),
        ),
    ]
