# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 00:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0010_auto_20170918_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaInstitucional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Compromisso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, null=True)),
                ('data', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='agendaprivada',
            name='agenda_ptr',
        ),
        migrations.RemoveField(
            model_name='agendaprivada',
            name='usuarios',
        ),
        migrations.RenameField(
            model_name='agenda',
            old_name='tarefa',
            new_name='descricao',
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='compromisso',
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='data_hora_Inicio',
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='agendas',
        ),
        migrations.AddField(
            model_name='agenda',
            name='tipo',
            field=models.CharField(choices=[('privada', 'privada'), ('publica', 'publica')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agenda',
            name='usuarios',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agenda.Usuario'),
        ),
        migrations.DeleteModel(
            name='AgendaPrivada',
        ),
        migrations.AddField(
            model_name='agendainstitucional',
            name='feriados',
            field=models.ManyToManyField(to='agenda.Compromisso'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='compromissos',
            field=models.ManyToManyField(to='agenda.Compromisso', verbose_name='compromissos'),
        ),
    ]
