# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 00:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0011_auto_20170918_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='compromissos',
            field=models.ManyToManyField(to='agenda.Compromisso'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='usuarios',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agenda.Usuario'),
        ),
    ]
