# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 23:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0015_auto_20170925_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='compartilhamento',
            name='compromissos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agenda.Compromisso'),
        ),
    ]
