# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 23:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agenda', '0016_compartilhamento_compromissos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='usuario',
        ),
        migrations.AddField(
            model_name='agenda',
            name='usuario',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
