# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 00:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agenda', '0018_auto_20170925_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='institucional',
            field=models.BooleanField(verbose_name='institucional'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='visivel',
            field=models.BooleanField(verbose_name='Visivel'),
        ),
        migrations.RemoveField(
            model_name='convite',
            name='convidado',
        ),
        migrations.AddField(
            model_name='convite',
            name='convidado',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
