# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 00:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0019_auto_20170925_2104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='convite',
            old_name='resposta',
            new_name='respostaConvite',
        ),
    ]
