# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0021_auto_20170925_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convite',
            name='respostaConvite',
        ),
        migrations.AddField(
            model_name='convite',
            name='aceitarConvite',
            field=models.BooleanField(default=True),
        ),
    ]
